version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm install
      - cd client && npm install
  build:
    commands:
      - cd client && npm run build && cd ../
artifacts:
  files:
    - "**/*"
